//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.Permissions.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public System.Guid PermissionId { get; set; }
        public string PermissionName { get; set; }
        public int ControlBusinessObjectType { get; set; }
        public System.Guid ControlBusinessObjectId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsDeny { get; set; }
        public string Remark { get; set; }
        public System.Guid ModuleId { get; set; }
        public Nullable<System.Guid> OperationId { get; set; }
        public System.Guid BusinessWorker_BusinessWorkerId { get; set; }
    
        public virtual BusinessWorker BusinessWorker { get; set; }
    }
}
