//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.Permissions.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Lorn.Permissions.DataModels;
    
    public partial class PermissionsEntities : DbContext
    {
        public PermissionsEntities()
            : base("name=PermissionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessWorker> BusinessWorkers { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PreLoadPermission> PreLoadPermissions { get; set; }
        public virtual DbSet<RBusinessWorker> RBusinessWorkers { get; set; }
    }
}
