//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.Permissions.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreLoadPermission
    {
        public System.Guid PreLoadPermissionId { get; set; }
        public int ControlBusinessObjectType { get; set; }
        public System.Guid ControlBusinessObjectId { get; set; }
        public System.Guid ModuleId { get; set; }
        public Nullable<System.Guid> OperationId { get; set; }
        public string Description { get; set; }
    }
}
