//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.Permissions.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBusinessWorker
    {
        public System.Guid RBusinessWokerId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsDeny { get; set; }
        public string Remark { get; set; }
        public System.Guid ParentBusinessWorker_BusinessWorkerId { get; set; }
        public System.Guid ChildBusinessWorker_BusinessWorkerId { get; set; }
    
        public virtual BusinessWorker ChildBusinessWorker { get; set; }
        public virtual BusinessWorker ParentBusinessWorker { get; set; }
    }
}
