//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// AdMaterial
    /// </summary>
    public partial class AdMaterial
    {
        public AdMaterial()
        {
            this.AdMaterialFormInfos = new HashSet<AdMaterialFormInfo>();
            this.AdSpotPlanThirdMonitorCodes = new HashSet<AdSpotPlanThirdMonitorCode>();
            this.MaterialAssigns = new HashSet<AdMaterialAssign>();
            this.FrequencyControls = new HashSet<FrequencyControl>();
        }
    
        /// <summary>
        /// AdMaterialId
        /// </summary>
        public System.Guid AdMaterialId { get; set; }
        /// <summary>
        /// AdMasterPlanId
        /// </summary>
        public Nullable<System.Guid> AdMasterPlanId { get; set; }
        /// <summary>
        /// MaterialCode
        /// </summary>
        public string MaterialCode { get; set; }
        /// <summary>
        /// Enabled
        /// </summary>
        public bool Enabled { get; set; }
        /// <summary>
        /// CreativeTypeId
        /// </summary>
        public System.Guid CreativeTypeId { get; set; }
        /// <summary>
        /// TimeLength
        /// </summary>
        public Nullable<System.TimeSpan> TimeLength { get; set; }
        /// <summary>
        /// Height
        /// </summary>
        public Nullable<int> Height { get; set; }
        /// <summary>
        /// Width
        /// </summary>
        public Nullable<int> Width { get; set; }
        /// <summary>
        /// AspectRatioId
        /// </summary>
        public Nullable<System.Guid> AspectRatioId { get; set; }
        /// <summary>
        /// ExtData
        /// </summary>
        public string ExtData { get; set; }
        /// <summary>
        /// UpdateTime
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// MediaId
        /// </summary>
        public System.Guid MediaId { get; set; }
    
         /// <summary>
        /// 广告物料表单信息
        /// </summary>
        public virtual ICollection<AdMaterialFormInfo> AdMaterialFormInfos { get; set; }
         /// <summary>
        /// AdSpotPlanThirdMonitorCodes
        /// </summary>
        public virtual ICollection<AdSpotPlanThirdMonitorCode> AdSpotPlanThirdMonitorCodes { get; set; }
         /// <summary>
        /// MaterialAssigns
        /// </summary>
        public virtual ICollection<AdMaterialAssign> MaterialAssigns { get; set; }
         /// <summary>
        /// FrequencyControls
        /// </summary>
        public virtual ICollection<FrequencyControl> FrequencyControls { get; set; }
    }
}
