//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 广告物料表单信息
    /// </summary>
    public partial class AdMaterialFormInfo
    {
        /// <summary>
        /// AdMaterialFormInfoId
        /// </summary>
        public System.Guid AdMaterialFormInfoId { get; set; }
        /// <summary>
        /// CreativeTypeFormdefinitionId
        /// </summary>
        public System.Guid CreativeTypeFormdefinitionId { get; set; }
        /// <summary>
        /// Value
        /// </summary>
        public string Value { get; set; }
        /// <summary>
        /// SortNo
        /// </summary>
        public Nullable<int> SortNo { get; set; }
        /// <summary>
        /// AdMaterial_AdMaterialId
        /// </summary>
        public System.Guid AdMaterial_AdMaterialId { get; set; }
    
         /// <summary>
        /// AdMaterial
        /// </summary>
        public virtual AdMaterial AdMaterial { get; set; }
    }
}
