//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// AdMaterialAssign
    /// </summary>
    public partial class AdMaterialAssign
    {
        /// <summary>
        /// MaterialAssignId
        /// </summary>
        public System.Guid MaterialAssignId { get; set; }
        /// <summary>
        /// MicroSlideshowSequenceNo
        /// </summary>
        public Nullable<int> MicroSlideshowSequenceNo { get; set; }
    
         /// <summary>
        /// AdSpotPlanDetail
        /// </summary>
        public virtual AdSpotPlanDetail AdSpotPlanDetail { get; set; }
         /// <summary>
        /// AdMaterial
        /// </summary>
        public virtual AdMaterial AdMaterial { get; set; }
    }
}
