//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// AdSpotPlanThirdMonitorCode
    /// </summary>
    public partial class AdSpotPlanThirdMonitorCode
    {
        /// <summary>
        /// SpotPlanThirdMonitorCodeId
        /// </summary>
        public System.Guid SpotPlanThirdMonitorCodeId { get; set; }
        /// <summary>
        /// AdPositionId
        /// </summary>
        public Nullable<System.Guid> AdPositionId { get; set; }
        /// <summary>
        /// AdSpotPlanEdition_AdSpotPlanEditionId
        /// </summary>
        public Nullable<System.Guid> AdSpotPlanEdition_AdSpotPlanEditionId { get; set; }
        /// <summary>
        /// AdMaterial_AdMaterialId
        /// </summary>
        public Nullable<System.Guid> AdMaterial_AdMaterialId { get; set; }
        /// <summary>
        /// SpotDate
        /// </summary>
        public Nullable<System.DateTime> SpotDate { get; set; }
    
         /// <summary>
        /// AdMaterial
        /// </summary>
        public virtual AdMaterial AdMaterial { get; set; }
         /// <summary>
        /// AdSpotPlanEdition
        /// </summary>
        public virtual AdSpotPlanEdition AdSpotPlanEdition { get; set; }
         /// <summary>
        /// ThirdMonitorCode
        /// </summary>
        public virtual ThirdMonitorCode ThirdMonitorCode { get; set; }
         /// <summary>
        /// AdSpotPlanGroup
        /// </summary>
        public virtual AdSpotPlanGroup AdSpotPlanGroup { get; set; }
    }
}
