//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 广告投放计划
    /// </summary>
    public partial class AdSpotPlanEdition
    {
        public AdSpotPlanEdition()
        {
            this.AdSpotPlanGroups = new HashSet<AdSpotPlanGroup>();
            this.AdSpotPlanThirdMonitorCodes = new HashSet<AdSpotPlanThirdMonitorCode>();
            this.FrequencyControls = new HashSet<FrequencyControl>();
            this.RedirectConditions = new HashSet<RedirectCondition>();
        }
    
        /// <summary>
        /// AdSpotPlanEditionId
        /// </summary>
        public System.Guid AdSpotPlanEditionId { get; set; }
        /// <summary>
        /// EditionNo
        /// </summary>
        public int EditionNo { get; set; }
        /// <summary>
        /// Priority
        /// </summary>
        public int Priority { get; set; }
        /// <summary>
        /// CategoryExclusive
        /// </summary>
        public bool CategoryExclusive { get; set; }
        /// <summary>
        /// 产品类别Id
        /// </summary>
        public Nullable<System.Guid> ProductCategoryId { get; set; }
        /// <summary>
        /// MonitorCompanyId
        /// </summary>
        public Nullable<System.Guid> MonitorCompanyId { get; set; }
        /// <summary>
        /// StartDate
        /// </summary>
        public System.DateTime StartDate { get; set; }
        /// <summary>
        /// EndDate
        /// </summary>
        public System.DateTime EndDate { get; set; }
        /// <summary>
        /// EditionStatus
        /// </summary>
        public Lorn.ADSP.Common.DataModels.PlanStatus EditionStatus { get; set; }
        /// <summary>
        /// BudgetAmount
        /// </summary>
        public decimal BudgetAmount { get; set; }
        /// <summary>
        /// PackageDiscount
        /// </summary>
        public decimal PackageDiscount { get; set; }
        /// <summary>
        /// Remark
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// AdSpotPlan_AdSpotPlanId
        /// </summary>
        public System.Guid AdSpotPlan_AdSpotPlanId { get; set; }
        /// <summary>
        /// AdSpotPlanType_AdSpotPlanTypeId
        /// </summary>
        public System.Guid AdSpotPlanType_AdSpotPlanTypeId { get; set; }
        /// <summary>
        /// IpLibrary_IpLibraryId
        /// </summary>
        public Nullable<System.Guid> IpLibrary_IpLibraryId { get; set; }
    
         /// <summary>
        /// AdSpotPlan
        /// </summary>
        public virtual AdSpotPlan AdSpotPlan { get; set; }
         /// <summary>
        /// AdSpotPlanGroups
        /// </summary>
        public virtual ICollection<AdSpotPlanGroup> AdSpotPlanGroups { get; set; }
         /// <summary>
        /// AdSpotPlanThirdMonitorCodes
        /// </summary>
        public virtual ICollection<AdSpotPlanThirdMonitorCode> AdSpotPlanThirdMonitorCodes { get; set; }
         /// <summary>
        /// AdSpotPlanType
        /// </summary>
        public virtual AdSpotPlanType AdSpotPlanType { get; set; }
         /// <summary>
        /// IpLibrary
        /// </summary>
        public virtual IpLibrary IpLibrary { get; set; }
         /// <summary>
        /// FrequencyControls
        /// </summary>
        public virtual ICollection<FrequencyControl> FrequencyControls { get; set; }
         /// <summary>
        /// 结算监测类型
        /// </summary>
        public virtual MonitorType ValuationMonitorType { get; set; }
         /// <summary>
        /// RedirectConditions
        /// </summary>
        public virtual ICollection<RedirectCondition> RedirectConditions { get; set; }
    }
}
