//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// AdSpotPlanType
    /// </summary>
    public partial class AdSpotPlanType
    {
        public AdSpotPlanType()
        {
            this.AdSpotPlanEditions = new HashSet<AdSpotPlanEdition>();
        }
    
        /// <summary>
        /// AdSpotPlanTypeId
        /// </summary>
        public System.Guid AdSpotPlanTypeId { get; set; }
        /// <summary>
        /// AdSpotPlanTypeName
        /// </summary>
        public string AdSpotPlanTypeName { get; set; }
        /// <summary>
        /// Description
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Priority
        /// </summary>
        public short Priority { get; set; }
        /// <summary>
        /// MediaId
        /// </summary>
        public Nullable<System.Guid> MediaId { get; set; }
    
         /// <summary>
        /// AdSpotPlanEditions
        /// </summary>
        public virtual ICollection<AdSpotPlanEdition> AdSpotPlanEditions { get; set; }
    }
}
