//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// AdSpotPlanGroup
    /// </summary>
    public partial class AdSpotPlanGroup
    {
        public AdSpotPlanGroup()
        {
            this.AdSpotPlanDetails = new HashSet<AdSpotPlanDetail>();
            this.RedirectConditions = new HashSet<RedirectCondition>();
            this.FrequencyControls = new HashSet<FrequencyControl>();
            this.AdSpotPlanThirdMonitorCodes = new HashSet<AdSpotPlanThirdMonitorCode>();
        }
    
        /// <summary>
        /// SpotPlanGroupId
        /// </summary>
        public System.Guid SpotPlanGroupId { get; set; }
        /// <summary>
        /// SpotPlanGroupName
        /// </summary>
        public string SpotPlanGroupName { get; set; }
        /// <summary>
        /// AdSpotPlanEdition_AdSpotPlanEditionId
        /// </summary>
        public System.Guid AdSpotPlanEdition_AdSpotPlanEditionId { get; set; }
    
         /// <summary>
        /// AdSpotPlanDetails
        /// </summary>
        public virtual ICollection<AdSpotPlanDetail> AdSpotPlanDetails { get; set; }
         /// <summary>
        /// AdSpotPlanEdition
        /// </summary>
        public virtual AdSpotPlanEdition AdSpotPlanEdition { get; set; }
         /// <summary>
        /// RedirectConditions
        /// </summary>
        public virtual ICollection<RedirectCondition> RedirectConditions { get; set; }
         /// <summary>
        /// FrequencyControls
        /// </summary>
        public virtual ICollection<FrequencyControl> FrequencyControls { get; set; }
         /// <summary>
        /// AdSpotPlanThirdMonitorCodes
        /// </summary>
        public virtual ICollection<AdSpotPlanThirdMonitorCode> AdSpotPlanThirdMonitorCodes { get; set; }
    }
}
