//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// AdSpotPlanDetail
    /// </summary>
    public partial class AdSpotPlanDetail
    {
        public AdSpotPlanDetail()
        {
            this.MaterialAssigns = new HashSet<AdMaterialAssign>();
        }
    
        /// <summary>
        /// AdPositionDetailId
        /// </summary>
        public System.Guid AdPositionDetailId { get; set; }
        /// <summary>
        /// SpotDate
        /// </summary>
        public System.DateTime SpotDate { get; set; }
        /// <summary>
        /// AdSpotPlanGroupId
        /// </summary>
        public System.Guid AdSpotPlanGroupId { get; set; }
        /// <summary>
        /// 广告位Id
        /// </summary>
        public string AdPositionId { get; set; }
        /// <summary>
        /// SaleType
        /// </summary>
        public  Lorn.ADSP.Common.DataModels.SaleType SaleType { get; set; }
        /// <summary>
        /// AdPositionFormat
        /// </summary>
        public string AdPositionFormat { get; set; }
        /// <summary>
        /// AdPositionUrl
        /// </summary>
        public string AdPositionUrl { get; set; }
        /// <summary>
        /// PlanTrafficRatio
        /// </summary>
        public Nullable<int> PlanTrafficRatio { get; set; }
        /// <summary>
        /// PlanImpressionNumber
        /// </summary>
        public Nullable<long> PlanImpressionNumber { get; set; }
        /// <summary>
        /// PlanClickNumber
        /// </summary>
        public Nullable<long> PlanClickNumber { get; set; }
        /// <summary>
        /// MacroSlideshowSequenceNo
        /// </summary>
        public Nullable<int> MacroSlideshowSequenceNo { get; set; }
        /// <summary>
        /// MicroSlideshowType
        /// </summary>
        public Nullable<Lorn.ADSP.Common.DataModels.MicroSlideshowType> MicroSlideshowType { get; set; }
        /// <summary>
        /// PublishPrice
        /// </summary>
        public decimal PublishPrice { get; set; }
        /// <summary>
        /// NetPrice
        /// </summary>
        public decimal NetPrice { get; set; }
        /// <summary>
        /// PriceType
        /// </summary>
        public  Lorn.ADSP.Common.DataModels.PriceUnit PriceType { get; set; }
        /// <summary>
        /// ComsumeType
        /// </summary>
        public Lorn.ADSP.Common.DataModels.ConsumeType ComsumeType { get; set; }
        /// <summary>
        /// 广告尺寸Id
        /// </summary>
        public Nullable<System.Guid> AdPositionSizeId { get; set; }
        /// <summary>
        /// 广告位置Id
        /// </summary>
        public Nullable<System.Guid> AdLocationId { get; set; }
    
         /// <summary>
        /// AdSpotPlanGroup
        /// </summary>
        public virtual AdSpotPlanGroup AdSpotPlanGroup { get; set; }
         /// <summary>
        /// MaterialAssigns
        /// </summary>
        public virtual ICollection<AdMaterialAssign> MaterialAssigns { get; set; }
    }
}
