//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FrequencyControl
    /// </summary>
    public partial class FrequencyControl
    {
        public FrequencyControl()
        {
            this.AdSpotPlanEditions = new HashSet<AdSpotPlanEdition>();
            this.AdSpotPlanGroups = new HashSet<AdSpotPlanGroup>();
            this.AdMaterials = new HashSet<AdMaterial>();
            this.FrequencyControlDetails = new HashSet<FrequencyControlDetail>();
        }
    
        /// <summary>
        /// FrequencyControlId
        /// </summary>
        public System.Guid FrequencyControlId { get; set; }
        /// <summary>
        /// FrequencyControlName
        /// </summary>
        public string FrequencyControlName { get; set; }
        /// <summary>
        /// FrequencyControlDetail
        /// </summary>
        public string FrequencyControlDetail { get; set; }
        /// <summary>
        /// MediaId
        /// </summary>
        public System.Guid MediaId { get; set; }
    
         /// <summary>
        /// AdSpotPlanEditions
        /// </summary>
        public virtual ICollection<AdSpotPlanEdition> AdSpotPlanEditions { get; set; }
         /// <summary>
        /// AdSpotPlanGroups
        /// </summary>
        public virtual ICollection<AdSpotPlanGroup> AdSpotPlanGroups { get; set; }
         /// <summary>
        /// AdMaterials
        /// </summary>
        public virtual ICollection<AdMaterial> AdMaterials { get; set; }
         /// <summary>
        /// FrequencyControlDetails
        /// </summary>
        public virtual ICollection<FrequencyControlDetail> FrequencyControlDetails { get; set; }
    }
}
