//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FrequencyControlDetail
    /// </summary>
    public partial class FrequencyControlDetail
    {
        /// <summary>
        /// FrequencyControlDetailId
        /// </summary>
        public System.Guid FrequencyControlDetailId { get; set; }
        /// <summary>
        /// FrequencyControlPeriod
        /// </summary>
        public Lorn.ADSP.Common.DataModels.FrequencyControlPeriod FrequencyControlPeriod { get; set; }
        /// <summary>
        /// PeriodNumber
        /// </summary>
        public int PeriodNumber { get; set; }
        /// <summary>
        /// MaxCount
        /// </summary>
        public Nullable<int> MaxCount { get; set; }
        /// <summary>
        /// MinCount
        /// </summary>
        public Nullable<int> MinCount { get; set; }
    
         /// <summary>
        /// FrequencyControl
        /// </summary>
        public virtual FrequencyControl FrequencyControl { get; set; }
    }
}
