//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// IpLibrary
    /// </summary>
    public partial class IpLibrary
    {
        public IpLibrary()
        {
            this.AdSpotPlanEditions = new HashSet<AdSpotPlanEdition>();
        }
    
        /// <summary>
        /// IpLibraryId
        /// </summary>
        public System.Guid IpLibraryId { get; set; }
        /// <summary>
        /// IpLibraryCode
        /// </summary>
        public string IpLibraryCode { get; set; }
        /// <summary>
        /// IpLibraryName
        /// </summary>
        public string IpLibraryName { get; set; }
        /// <summary>
        /// Description
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Enabled
        /// </summary>
        public bool Enabled { get; set; }
        /// <summary>
        /// MediaId
        /// </summary>
        public Nullable<System.Guid> MediaId { get; set; }
    
         /// <summary>
        /// AdSpotPlanEditions
        /// </summary>
        public virtual ICollection<AdSpotPlanEdition> AdSpotPlanEditions { get; set; }
    }
}
