//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// MonitorType
    /// </summary>
    public partial class MonitorType
    {
        public MonitorType()
        {
            this.AdSpotPlanEditions = new HashSet<AdSpotPlanEdition>();
            this.ThirdMonitorCodes = new HashSet<ThirdMonitorCode>();
        }
    
        /// <summary>
        /// MonitorTypeId
        /// </summary>
        public System.Guid MonitorTypeId { get; set; }
        /// <summary>
        /// MonitorTypeName
        /// </summary>
        public string MonitorTypeName { get; set; }
        /// <summary>
        /// MonitorTypeCode
        /// </summary>
        public string MonitorTypeCode { get; set; }
        /// <summary>
        /// Description
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// MediaId
        /// </summary>
        public Nullable<System.Guid> MediaId { get; set; }
        /// <summary>
        /// PriceUnit
        /// </summary>
        public  Lorn.ADSP.Common.DataModels.PriceUnit PriceUnit { get; set; }
    
         /// <summary>
        /// AdSpotPlanEditions
        /// </summary>
        public virtual ICollection<AdSpotPlanEdition> AdSpotPlanEditions { get; set; }
         /// <summary>
        /// ThirdMonitorCodes
        /// </summary>
        public virtual ICollection<ThirdMonitorCode> ThirdMonitorCodes { get; set; }
    }
}
