//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.AM.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// RedirectConditionDetail
    /// </summary>
    public partial class RedirectConditionDetail
    {
        /// <summary>
        /// RedirectConditionDetailId
        /// </summary>
        public System.Guid RedirectConditionDetailId { get; set; }
        /// <summary>
        /// StartValue
        /// </summary>
        public Nullable<double> StartValue { get; set; }
        /// <summary>
        /// EndValue
        /// </summary>
        public Nullable<double> EndValue { get; set; }
        /// <summary>
        /// RedirectCondition_RedirectConditionId
        /// </summary>
        public System.Guid RedirectCondition_RedirectConditionId { get; set; }
        /// <summary>
        /// CustomKey
        /// </summary>
        public string CustomKey { get; set; }
        /// <summary>
        /// CustomValue
        /// </summary>
        public string CustomValue { get; set; }
        /// <summary>
        /// RedirectConditionDefinitionId
        /// </summary>
        public Nullable<System.Guid> RedirectConditionDefinitionId { get; set; }
    
         /// <summary>
        /// RedirectCondition
        /// </summary>
        public virtual RedirectCondition RedirectCondition { get; set; }
    }
}
