//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Lorn.ADSP.Common.DataModels;
    
    public partial class AdInfrastructureDataContainer : DbContext
    {
        public AdInfrastructureDataContainer()
            : base("name=AdInfrastructureDataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdPositionAspectRatio> AdPositionAspectRatios { get; set; }
        public virtual DbSet<AdPositionGroup> AdPositionGroups { get; set; }
        public virtual DbSet<AdPosition> AdPositions { get; set; }
        public virtual DbSet<AdPositionSize> AdPositionSizes { get; set; }
        public virtual DbSet<AdTemplateRelationship> AdTemplateRelationships { get; set; }
        public virtual DbSet<AdTemplate> AdTemplates { get; set; }
        public virtual DbSet<CreativeTypeFormDefinition> CreativeTypeFormDefinitions { get; set; }
        public virtual DbSet<CreativeType> CreativeTypes { get; set; }
        public virtual DbSet<MaterialFormat> MaterialFormats { get; set; }
        public virtual DbSet<Media> Medium { get; set; }
        public virtual DbSet<RedirectConditionDefinition> RedirectConditionDefinitions { get; set; }
        public virtual DbSet<RedirectDimension> RedirectDimensions { get; set; }
        public virtual DbSet<AdProcessPipline> AdProcessPiplines { get; set; }
        public virtual DbSet<AdLocation> AdLocations { get; set; }
    }
}
