//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 广告位
    /// </summary>
    public partial class AdPosition
    {
        partial void InitPKDefaultValues();
        public AdPosition()
        {
    		InitPKDefaultValues();
            this.AdPositionAspectRatios = new HashSet<AdPositionAspectRatio>();
            this.AdPositionGroups = new HashSet<AdPositionGroup>();
            this.AdTemplateRelationships = new HashSet<AdTemplateRelationship>();
            this.CreativeTypes = new HashSet<CreativeType>();
    
    	}
        /// <summary>
        /// AdPositionId
        /// </summary>
        public System.Guid AdPositionId { get; set; }
        /// <summary>
        /// 广告位代码
        /// </summary>
        public string AdPositionCode { get; set; }
        /// <summary>
        /// 广告位名称
        /// </summary>
        public string AdPositionName { get; set; }
        /// <summary>
        /// 广告位Url
        /// </summary>
        public string AdPositionUrl { get; set; }
        /// <summary>
        /// 广告位描述
        /// </summary>
        public string AdPositionDesc { get; set; }
        /// <summary>
        /// 最大轮播次数
        /// </summary>
        public Nullable<short> MaxSlideshowNumber { get; set; }
        /// <summary>
        /// AdPositionSize_AdPositionSizeId
        /// </summary>
        public Nullable<System.Guid> AdPositionSize_AdPositionSizeId { get; set; }
        /// <summary>
        /// Medium_MediaId
        /// </summary>
        public System.Guid Medium_MediaId { get; set; }
        /// <summary>
        /// 默认价格单位
        /// </summary>
        public PriceUnit DefaultPriceUnit { get; set; }
        /// <summary>
        /// 最大返回广告数
        /// </summary>
        public int MaxReturnAdCount { get; set; }
        /// <summary>
        /// 广告位类型
        /// </summary>
        public AdPositionType PositionType { get; set; }
    
         /// <summary>
        /// 广告位支持高宽比
        /// </summary>
        public virtual ICollection<AdPositionAspectRatio> AdPositionAspectRatios { get; set; }
         /// <summary>
        /// 所属广告位组
        /// </summary>
        public virtual ICollection<AdPositionGroup> AdPositionGroups { get; set; }
         /// <summary>
        /// 广告模板关系
        /// </summary>
        public virtual ICollection<AdTemplateRelationship> AdTemplateRelationships { get; set; }
         /// <summary>
        /// 广告位尺寸
        /// </summary>
        public virtual AdPositionSize AdPositionSize { get; set; }
         /// <summary>
        /// 所属媒体
        /// </summary>
        public virtual Media Media { get; set; }
         /// <summary>
        /// 支持创意类型
        /// </summary>
        public virtual ICollection<CreativeType> CreativeTypes { get; set; }
         /// <summary>
        /// 广告位处理管线
        /// </summary>
        public virtual AdProcessPipline AdProcessPipline { get; set; }
         /// <summary>
        /// AdLocation
        /// </summary>
        public virtual AdLocation AdLocation { get; set; }
    }
}
