//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// AdPositionSize
    /// </summary>
    public partial class AdPositionSize
    {
        partial void InitPKDefaultValues();
        public AdPositionSize()
        {
    		InitPKDefaultValues();
            this.AdPositions = new HashSet<AdPosition>();
    
    	}
        /// <summary>
        /// AdPositionSizeId
        /// </summary>
        public System.Guid AdPositionSizeId { get; set; }
        /// <summary>
        /// Height
        /// </summary>
        public int Height { get; set; }
        /// <summary>
        /// Width
        /// </summary>
        public int Width { get; set; }
    
         /// <summary>
        /// AdPositions
        /// </summary>
        public virtual ICollection<AdPosition> AdPositions { get; set; }
         /// <summary>
        /// Media
        /// </summary>
        public virtual Media Media { get; set; }
    }
}
