//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// AdPositionGroup
    /// </summary>
    public partial class AdPositionGroup
    {
        partial void InitPKDefaultValues();
        public AdPositionGroup()
        {
    		InitPKDefaultValues();
            this.AdPositions = new HashSet<AdPosition>();
    
    	}
        /// <summary>
        /// AdPositionGroupId
        /// </summary>
        public System.Guid AdPositionGroupId { get; set; }
        /// <summary>
        /// AdPositionGroupName
        /// </summary>
        public string AdPositionGroupName { get; set; }
        /// <summary>
        /// Description
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// AdPositionGroupCode
        /// </summary>
        public string AdPositionGroupCode { get; set; }
    
         /// <summary>
        /// AdPositions
        /// </summary>
        public virtual ICollection<AdPosition> AdPositions { get; set; }
         /// <summary>
        /// Media
        /// </summary>
        public virtual Media Media { get; set; }
         /// <summary>
        /// AdProcessPipline
        /// </summary>
        public virtual AdProcessPipline AdProcessPipline { get; set; }
    }
}
