//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 广告处理管线定义
    /// </summary>
    public partial class AdProcessPipline
    {
        partial void InitPKDefaultValues();
        public AdProcessPipline()
        {
    		InitPKDefaultValues();
            this.AdPositions = new HashSet<AdPosition>();
            this.AdPositionGroups = new HashSet<AdPositionGroup>();
    
    	}
        /// <summary>
        /// AdProcessPiplineId
        /// </summary>
        public System.Guid AdProcessPiplineId { get; set; }
        /// <summary>
        /// 广告处理管线名称
        /// </summary>
        public string PiplineName { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 配置文件名
        /// </summary>
        public string ConfigfileName { get; set; }
    
         /// <summary>
        /// 广告位
        /// </summary>
        public virtual ICollection<AdPosition> AdPositions { get; set; }
         /// <summary>
        /// 所属媒体
        /// </summary>
        public virtual Media Media { get; set; }
         /// <summary>
        /// 广告位组
        /// </summary>
        public virtual ICollection<AdPositionGroup> AdPositionGroups { get; set; }
    }
}
