//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 广告模板
    /// </summary>
    public partial class AdTemplate
    {
        partial void InitPKDefaultValues();
        public AdTemplate()
        {
    		InitPKDefaultValues();
            this.AdTemplateRelationships = new HashSet<AdTemplateRelationship>();
    
    	}
        /// <summary>
        /// AdTemplateId
        /// </summary>
        public System.Guid AdTemplateId { get; set; }
        /// <summary>
        /// 模板名称
        /// </summary>
        public string AdTemplateName { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 模板内容
        /// </summary>
        public string TemplateContent { get; set; }
        /// <summary>
        /// 序列化器Id
        /// </summary>
        public System.Guid SerializerId { get; set; }
        /// <summary>
        /// 是否是广告位模板
        /// </summary>
        public bool IsAdPositionTemplate { get; set; }
    
         /// <summary>
        /// 广告模板关系
        /// </summary>
        public virtual ICollection<AdTemplateRelationship> AdTemplateRelationships { get; set; }
         /// <summary>
        /// 所属媒体
        /// </summary>
        public virtual Media Media { get; set; }
    }
}
