//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// AdTemplateRelationship
    /// </summary>
    public partial class AdTemplateRelationship
    {
        partial void InitPKDefaultValues();
        public AdTemplateRelationship()
        {
    		InitPKDefaultValues();
    	}
        /// <summary>
        /// AdPositionRelationId
        /// </summary>
        public System.Guid AdPositionRelationId { get; set; }
        /// <summary>
        /// AdPosition_AdPositionId
        /// </summary>
        public Nullable<System.Guid> AdPosition_AdPositionId { get; set; }
        /// <summary>
        /// RedirectConditionDefinition_RedirectConditionDefinitionId
        /// </summary>
        public Nullable<System.Guid> RedirectConditionDefinition_RedirectConditionDefinitionId { get; set; }
        /// <summary>
        /// CreativeType_CreativeTypeId
        /// </summary>
        public Nullable<System.Guid> CreativeType_CreativeTypeId { get; set; }
        /// <summary>
        /// AdTemplate_AdTemplateId
        /// </summary>
        public System.Guid AdTemplate_AdTemplateId { get; set; }
    
         /// <summary>
        /// AdPosition
        /// </summary>
        public virtual AdPosition AdPosition { get; set; }
         /// <summary>
        /// AdTemplate
        /// </summary>
        public virtual AdTemplate AdTemplate { get; set; }
         /// <summary>
        /// CreativeType
        /// </summary>
        public virtual CreativeType CreativeType { get; set; }
         /// <summary>
        /// RedirectConditionDefinition
        /// </summary>
        public virtual RedirectConditionDefinition RedirectConditionDefinition { get; set; }
    }
}
