//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// CreativeType
    /// </summary>
    public partial class CreativeType
    {
        partial void InitPKDefaultValues();
        public CreativeType()
        {
    		InitPKDefaultValues();
            this.CreativeTypeFormDefinitions = new HashSet<CreativeTypeFormDefinition>();
            this.AdTemplateRelationships = new HashSet<AdTemplateRelationship>();
            this.AdPosition = new HashSet<AdPosition>();
    
    	}
        /// <summary>
        /// CreativeTypeId
        /// </summary>
        public System.Guid CreativeTypeId { get; set; }
        /// <summary>
        /// CreativeTypeName
        /// </summary>
        public string CreativeTypeName { get; set; }
        /// <summary>
        /// CreativeTypeDesc
        /// </summary>
        public string CreativeTypeDesc { get; set; }
        /// <summary>
        /// DisplaySort
        /// </summary>
        public Nullable<int> DisplaySort { get; set; }
    
         /// <summary>
        /// CreativeTypeFormDefinitions
        /// </summary>
        public virtual ICollection<CreativeTypeFormDefinition> CreativeTypeFormDefinitions { get; set; }
         /// <summary>
        /// AdTemplateRelationships
        /// </summary>
        public virtual ICollection<AdTemplateRelationship> AdTemplateRelationships { get; set; }
         /// <summary>
        /// AdPosition
        /// </summary>
        public virtual ICollection<AdPosition> AdPosition { get; set; }
         /// <summary>
        /// Media
        /// </summary>
        public virtual Media Media { get; set; }
    }
}
