//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// MaterialFormat
    /// </summary>
    public partial class MaterialFormat
    {
        partial void InitPKDefaultValues();
        public MaterialFormat()
        {
    		InitPKDefaultValues();
            this.CreativeTypeFormDefinitions = new HashSet<CreativeTypeFormDefinition>();
    
    	}
        /// <summary>
        /// MaterialFormatId
        /// </summary>
        public System.Guid MaterialFormatId { get; set; }
        /// <summary>
        /// MaterialFormatName
        /// </summary>
        public string MaterialFormatName { get; set; }
        /// <summary>
        /// MaterialFormatFileExtention
        /// </summary>
        public string MaterialFormatFileExtention { get; set; }
        /// <summary>
        /// MaterialFormatDesc
        /// </summary>
        public string MaterialFormatDesc { get; set; }
    
         /// <summary>
        /// CreativeTypeFormDefinitions
        /// </summary>
        public virtual ICollection<CreativeTypeFormDefinition> CreativeTypeFormDefinitions { get; set; }
         /// <summary>
        /// Media
        /// </summary>
        public virtual Media Media { get; set; }
    }
}
