//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 媒体
    /// </summary>
    public partial class Media
    {
        partial void InitPKDefaultValues();
        public Media()
        {
    		InitPKDefaultValues();
            this.AdPositions = new HashSet<AdPosition>();
            this.AdPositionSizes = new HashSet<AdPositionSize>();
            this.AdTemplates = new HashSet<AdTemplate>();
            this.AdPositionAspectRatios = new HashSet<AdPositionAspectRatio>();
            this.AdProcessPiplines = new HashSet<AdProcessPipline>();
            this.MaterialFormats = new HashSet<MaterialFormat>();
            this.AdPositionGroups = new HashSet<AdPositionGroup>();
            this.CreativeTypes = new HashSet<CreativeType>();
            this.RedirectDimensions = new HashSet<RedirectDimension>();
            this.RedirectConditionDefinitions = new HashSet<RedirectConditionDefinition>();
    
    	}
        /// <summary>
        /// MediaId
        /// </summary>
        public System.Guid MediaId { get; set; }
        /// <summary>
        /// 媒体名称
        /// </summary>
        public string MediaName { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 安全码
        /// </summary>
        public System.Guid SecureKey { get; set; }
    
         /// <summary>
        /// 广告位
        /// </summary>
        public virtual ICollection<AdPosition> AdPositions { get; set; }
         /// <summary>
        /// 广告位尺寸
        /// </summary>
        public virtual ICollection<AdPositionSize> AdPositionSizes { get; set; }
         /// <summary>
        /// 广告模板
        /// </summary>
        public virtual ICollection<AdTemplate> AdTemplates { get; set; }
         /// <summary>
        /// 广告位高宽比
        /// </summary>
        public virtual ICollection<AdPositionAspectRatio> AdPositionAspectRatios { get; set; }
         /// <summary>
        /// 广告处理管线
        /// </summary>
        public virtual ICollection<AdProcessPipline> AdProcessPiplines { get; set; }
         /// <summary>
        /// 素材格式
        /// </summary>
        public virtual ICollection<MaterialFormat> MaterialFormats { get; set; }
         /// <summary>
        /// 广告位组
        /// </summary>
        public virtual ICollection<AdPositionGroup> AdPositionGroups { get; set; }
         /// <summary>
        /// 创意类型
        /// </summary>
        public virtual ICollection<CreativeType> CreativeTypes { get; set; }
         /// <summary>
        /// 定向维度
        /// </summary>
        public virtual ICollection<RedirectDimension> RedirectDimensions { get; set; }
         /// <summary>
        /// 定向条件定义
        /// </summary>
        public virtual ICollection<RedirectConditionDefinition> RedirectConditionDefinitions { get; set; }
    }
}
