//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    
    /// <summary>
    /// PriceUnit
    /// </summary>
    public enum PriceUnit : int
    {
        CPT = 0,
        CPM = 1,
        CPC = 2
    }
}
