//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// RedirectConditionDefinition
    /// </summary>
    public partial class RedirectConditionDefinition
    {
        partial void InitPKDefaultValues();
        public RedirectConditionDefinition()
        {
    		InitPKDefaultValues();
            this.AdTemplateRelationships = new HashSet<AdTemplateRelationship>();
            this.ChildRedirectConditionDefinitions = new HashSet<RedirectConditionDefinition>();
    
    	}
        /// <summary>
        /// RedirectConditionDefinitionId
        /// </summary>
        public System.Guid RedirectConditionDefinitionId { get; set; }
        /// <summary>
        /// ConditionName
        /// </summary>
        public string ConditionName { get; set; }
        /// <summary>
        /// ConditionCode
        /// </summary>
        public string ConditionCode { get; set; }
        /// <summary>
        /// Value
        /// </summary>
        public Nullable<double> Value { get; set; }
        /// <summary>
        /// ConditionDesc
        /// </summary>
        public string ConditionDesc { get; set; }
        /// <summary>
        /// DisplaySort
        /// </summary>
        public Nullable<int> DisplaySort { get; set; }
        /// <summary>
        /// IsSystemBuild
        /// </summary>
        public bool IsSystemBuild { get; set; }
        /// <summary>
        /// RedirectDimension_RedirectDimensionId
        /// </summary>
        public System.Guid RedirectDimension_RedirectDimensionId { get; set; }
        /// <summary>
        /// ParentRedirectConditionDefinition_RedirectConditionDefinitionId
        /// </summary>
        public Nullable<System.Guid> ParentRedirectConditionDefinition_RedirectConditionDefinitionId { get; set; }
    
         /// <summary>
        /// AdTemplateRelationships
        /// </summary>
        public virtual ICollection<AdTemplateRelationship> AdTemplateRelationships { get; set; }
         /// <summary>
        /// ChildRedirectConditionDefinitions
        /// </summary>
        public virtual ICollection<RedirectConditionDefinition> ChildRedirectConditionDefinitions { get; set; }
         /// <summary>
        /// ParentRedirectConditionDefinition
        /// </summary>
        public virtual RedirectConditionDefinition ParentRedirectConditionDefinition { get; set; }
         /// <summary>
        /// RedirectDimension
        /// </summary>
        public virtual RedirectDimension RedirectDimension { get; set; }
         /// <summary>
        /// Media
        /// </summary>
        public virtual Media Media { get; set; }
    }
}
