//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorn.ADSP.Common.DataModels
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// RedirectDimension
    /// </summary>
    public partial class RedirectDimension
    {
        partial void InitPKDefaultValues();
        public RedirectDimension()
        {
    		InitPKDefaultValues();
            this.RedirectConditionDefinitions = new HashSet<RedirectConditionDefinition>();
    
    	}
        /// <summary>
        /// RedirectDimensionId
        /// </summary>
        public System.Guid RedirectDimensionId { get; set; }
        /// <summary>
        /// RedirectDimensionName
        /// </summary>
        public string RedirectDimensionName { get; set; }
        /// <summary>
        /// RedirectDimensionCode
        /// </summary>
        public string RedirectDimensionCode { get; set; }
        /// <summary>
        /// RedirectDimensionDesc
        /// </summary>
        public string RedirectDimensionDesc { get; set; }
        /// <summary>
        /// DisplaySort
        /// </summary>
        public Nullable<int> DisplaySort { get; set; }
        /// <summary>
        /// CanCustomKey
        /// </summary>
        public bool CanCustomKey { get; set; }
        /// <summary>
        /// CanCustomValue
        /// </summary>
        public bool CanCustomValue { get; set; }
    
         /// <summary>
        /// RedirectConditionDefinitions
        /// </summary>
        public virtual ICollection<RedirectConditionDefinition> RedirectConditionDefinitions { get; set; }
         /// <summary>
        /// Media
        /// </summary>
        public virtual Media Media { get; set; }
    }
}
